### ISSUE TITLE
Add endpoint to create a new MUC service

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-restAPI-plugin#130]
MUC rooms are organized over one or more MUC services. Typically, an XMPP domain uses only one service (Openfire defaults to the name 'conference' for this). It is possible, however, to have more than one MUC service.

The restAPI plugin has various endpoints to create MUC rooms, but it has no endpoints to create MUC services. Such an endpoint should be added.

**Comment by evdherberg** [comment]
I created the endpoint, see e231790. But how useful will it be to just have this `POST` without the possibility of querying what services are already available? It would be quite easy to at least create a `GET` that returns all currently existing MUC services. But I don't know if that would be out of scope for this issue.

**Comment by guusdk** [comment]
Go for it.
