### ISSUE TITLE
Defensively create collections in JAXB getters

### ISSUE THREAD

**Issue by evdherberg** [igniterealtime/openfire-restAPI-plugin#137]
The `POST /restapi/v1/chatrooms` encounters NPE's whenever one of the optional `List` elements is included in the payload. [Here](https://stackoverflow.com/q/31697885) it is suggested that JAXB does not use collection setters, so the collection getter should always return a non-null value. And, indeed, when I change the getter implementation to defensively create the list, the NPE disappears.

What puzzles me is that this must have occurred before, when the create room functionality was initially developed. So either this resource was added with virtually no testing, or something changed since then (JAXB versions?), or there is something very local to my development environment that causes this problem. Anyway, I thought best to raise this issue, and I will prepare a PR for the defensive creation of collections in the `MUCRoomEntity`.

**Comment by guusdk** [comment]
I wonder if the issue that you're trying to fix here is #15 in disguise. Let's see if #131 fixes the issue that you are running into. If that is the case, then we probably do not need further changes.

**Comment by evdherberg** [comment]
> I wonder if the issue that you're trying to fix here is #15 in disguise. Let's see if #131 fixes the issue that you are running into. If that is the case, then we probably do not need further changes.

That is indeed the case. In my last tests, without my changes to the entity, the problem was not there anymore. So probably #131 was the same problem. I am closing this issue and I will close the PR too.
