### ISSUE TITLE
Fix Maven build

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-restAPI-plugin#14]
To build plugins for Openfire 4.3.0 pom.xml should include repositories tags pointing to Archiva. If plugin has pages in Admin Console, web.xml should also be added.

For references:
https://github.com/igniterealtime/openfire-clientControl-plugin/pull/11

**Comment by guusdk** [comment]
@Redor I think this issue can now be closed, correct?

**Comment by Redor** [comment]
Yes. I will close it. Thy
