### ISSUE TITLE
Add new Certificate with API

### ISSUE THREAD

**Issue by ruicaramalho** [igniterealtime/openfire-restAPI-plugin#164]
it would be nice to be able to add a certificate to Openfire using API.

**Do you think its possible to do?**

Currently we have to run `keytool` in `\Program Files\Openfire\jre\bin`

~~~~dos

SET keystore="C:\Program Files\Openfire\resources\security\keystore"
SET pfx="C:\Certificates\openfire.pfx"
SET pfxpass=yourpfxpass
SET storepass=changeit

keytool -importkeystore -deststorepass %storepass% -destkeypass %storepass% -destkeystore %keystore% -srckeystore %pfx% -srcstoretype PKCS12 -srcstorepass %pfxpass% -noprompt -v
~~~~

**Comment by akrherz** [comment]
Note that the [openfire certificate plugin manager](https://igniterealtime.org/projects/openfire/plugins/1.1.0/certificatemanager/readme.html) exists for the general purpose of automation.

**Comment by guusdk** [comment]
I'm not sure if it would be wise to use a service that is protected by the same certificates to be used to update those certificates. As @akrherz wrote: the Openfire Certificate Manager plugin is probably a better choice here.

I'm going to close this issue for now. Feel free to re-open this with a compelling argument.
