### ISSUE TITLE
Admin console should not display 'null'

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-restAPI-plugin#17]
When a configuration change is saved, but no custom authentication filter classname is defined, the Admin Console page currently shows 'null'. That shouldn't happen.

![image](https://user-images.githubusercontent.com/4253898/53802925-6fa5b400-3f43-11e9-8164-d080909fb402.png)

**Comment by guusdk** [comment]
The same thing can happen with the shared secret.

**Comment by Redor** [comment]
Fixed in #18
