### ISSUE TITLE
REST API plugin does not work with Openfire 4.7.5

### ISSUE THREAD

**Issue by Jan1205** [igniterealtime/openfire-restAPI-plugin#178]
The REST API plugin does not work with Openfire 4.7.5. A request leads to a redirect to the login page.

**Comment by Fishbowler** [comment]
This was a change in defaults in 4.7.5 for security reasons.
Change the Openfire system property `adminConsole.access.allow-wildcards-in-excludes` to `true`

This will be fixed more gracefully with #177

**Comment by Jan1205** [comment]
@Fishbowler Thank you for the fast reply. The REST API plugin works perfekt now.
