### ISSUE TITLE
Could not apply modification to list of member

### ISSUE THREAD

**Issue by MrBytess** [igniterealtime/openfire-restAPI-plugin#181]
MUC sends an error message to join a member

http://192.168.1.55:9090/plugins/restapi/v1/chatrooms/30046/members/1003

Both users and chat rooms exist

Error Message:

{
    "resource": "30046",
    "message": "Could not apply modification to list of member",
    "exception": "NotAllowedException"
}

How to call correctly? What configuration is still needed?
![微信图片_20230918174257](https://github.com/igniterealtime/openfire-restAPI-plugin/assets/16519688/d84c68af-da4f-483f-ab9f-4c15bff53b7f)

**Comment by Fishbowler** [comment]
You're attempting to add a user whose local username is 1003 to a MUC named 30046, correct?

Which version of Openfire and the plugin are you using?

**Comment by Fishbowler** [comment]
Tried this out. This works for me.

Checked the code, this is returned under specific circumstances.

- Room is configured with "Only login with registered nickname"
- The user you're adding to the members is the only Owner (because at which point, you'd have no Owners)

**Comment by guusdk** [comment]
Closing this issue as it's been inactive, while Dan found the problem to be non-reproducible.
