### ISSUE TITLE
With Openfire 4.7.0, changes to chat rooms are not applied

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-restAPI-plugin#188]
When using the REST API to apply modifications to a MUC room (for example, add a user), then these changes do not appear to be pesisted. The REST API call that performs the modification returns without an error.

First, a query to see the current members of a MUC room named `muc2` (there are none):
```bash
guus@octarine:~$ curl -X 'GET' \
  'http://localhost:9092/plugins/restapi/v1/chatrooms/muc2/members' \
  -H 'accept: */*' \
  -H 'Authorization: test'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><members/> 
```

Add JID `john@example.org` to the collections of the MUC room:
```bash
guus@octarine:~$ curl -X 'POST' \
  'http://localhost:9092/plugins/restapi/v1/chatrooms/muc2/members/john%40example.org?servicename=conference&sendInvitations=false' \
  -H 'accept: */*' \
  -H 'Authorization: test' \
  -d ''  
```
In a new query for all current members of the room, it is expected to see `john@example.org` now, but tat does not happen:
```bash
guus@octarine:~$ curl -X 'GET' \
  'http://localhost:9092/plugins/restapi/v1/chatrooms/muc2/members' \
  -H 'accept: */*' \
  -H 'Authorization: test'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><members/>
```

In the admin console, the member does not show up either.

This likely has a relation to the MUC implementation refactoring that was part of Openfire 4.7.0. In that version a new API is introduced to synchronize MUC data across a cluster.

**Comment by guusdk** [comment]
A third party has confirmed that this change has the desired functional effect.

**Comment by brent85** [comment]
@16627602407 #
[72157722536323543_115a65b62cdc_part1.zip](https://github.com/igniterealtime/openfire-restAPI-plugin/files/14196833/72157722536323543_115a65b62cdc_part1.zip)

**Comment by brent85** [comment]
https://github.com/igniterealtime/openfire-restAPI-plugin/issues/188#issue-2052432458

> Member

Please reopen

**Comment by guusdk** [comment]
@brent85 your behavior in our source repository and on our forums is erratic. Unless you give me some kind of clear indication that you are indeed a person, and not some kind of malformed AI script running wild, I'm going to consider revoking your access to our resources.
