### ISSUE TITLE
Cannot update user entity via swagger

### ISSUE THREAD

**Issue by iarwen** [igniterealtime/openfire-restAPI-plugin#192]
![image](https://github.com/igniterealtime/openfire-restAPI-plugin/assets/6953523/dc3e6b9b-0eda-4900-909c-ea071ad0c49f)

**Comment by iarwen** [comment]
PR: https://github.com/igniterealtime/openfire-restAPI-plugin/pull/191

**Comment by guusdk** [comment]
Fixed with https://github.com/igniterealtime/openfire-restAPI-plugin/pull/191
