### ISSUE TITLE
Mvn clean install is failing

### ISSUE THREAD

**Issue by donpaulcj** [igniterealtime/openfire-restAPI-plugin#193]
I am not able to build the repo in my local. It is throwing could not find artifact Com.cenqua.shaj:shaj:pom0.5 igniterealtime error. Tried searching for this dependency but it is throwing 404 error in mvn repo

**Comment by guusdk** [comment]
I've tried to reproduce the problem in a clean environment. Both attempts worked without a problem. I've even explicitly verified that the artifact that you mention was downloaded, which it did:

```
Downloaded from atlassian-public: https://maven.atlassian.com/repository/public/com/cenqua/shaj/shaj/0.5/shaj-0.5.pom
```

I suspect that this is some kind of intermittent network issue that has now gone away, or something that is specific to your environment.
