### ISSUE TITLE
Retrieve chat room message history api not working 

### ISSUE THREAD

**Issue by harithm918** [igniterealtime/openfire-restAPI-plugin#198]
Retrieve chat room message history api not working for me. Can someone help

![image](https://github.com/user-attachments/assets/ea0d38be-13bf-4d06-ba81-76bacd12cca2)

**Comment by guusdk** [comment]
Please do not use this bug tracker for support questions. Instead, ask your questions in the ignite realtime community at https://discourse.igniterealtime.org/

Also, you will need to provide more context for anyone to be able to help you, other than.'it does not work'.
