### ISSUE TITLE
Please provide an address for reporting security vulnerabilities

### ISSUE THREAD

**Issue by rbsec** [igniterealtime/openfire-restAPI-plugin#199]
Hi,

Please can you provide an email address or other method for reporting security vulnerabilities? I tried using the `security@igniterealtime.org` address that I've seen mentioned previously, but emails to it get rejected:

> Your message couldn't be delivered. Despite repeated attempts to contact the recipient's email system it didn't respond.  
> [...]  
> [security@igniterealtime.org](mailto:security@igniterealtime.org)  
> Remote server returned '550 5.4.300 Message expired -> 451 4.7.1 Service unavailable - try again later'

**Comment by akrherz** [comment]
Hmmm, mail services seem to be up and running, as far as I can tell.  The VM could use a reboot and tried that now, can you kindly try the email again?

**Comment by akrherz** [comment]
@rbsec I just sent a test message to the list and it worked.  I don't see your message yet :(  If you want, you can forward it to me akrherz@iastate.edu and I'll redistribute it.

**Comment by akrherz** [comment]
I emailed you the postfix logs on our end that appear to be why your email is getting rejected

**Comment by rbsec** [comment]
Much appreciated - I'll dig into those offline.
