### ISSUE TITLE
API plugin - Openfire 4.0.9.0 - Missing Session Status STATUS_CLOSED

### ISSUE THREAD

**Issue by Devocity81** [igniterealtime/openfire-restAPI-plugin#200]
Installing Openfire 4.0.9.0 as well as the RestAPI Plugin 1.11.0 and we are receiving an error with the following information:
e[1;31mERRORe[m [Jetty-QTP-AdminConsole-192]: org.jivesoftware.openfire.container.PluginServlet - org.glassfish.jersey.server.ContainerException: java.lang.NoSuchFieldError: Class org.jivesoftware.openfire.session.Session does not have member field ‘org.jivesoftware.openfire.session.Session$Status STATUS_CLOSED’
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchFieldError: Class org.jivesoftware.openfire.session.Session does not have member field ‘org.jivesoftware.openfire.session.Session$Status STATUS_CLOSED’

Is Openfire missing something, or is the the restAPI plugin not compatible with the newest version of Openfire?

**Comment by guusdk** [comment]
That seems to be a compatibility issue with the latest version of Openfire, indeed. The unrecognized member field was removed from Openfire.

Does this problem occur only on specific REST endpoints?

**Comment by Devocity81** [comment]
We just started testing the upgrade to Openfire 4.0.9.0 with RestAPI Plugin 1.11.0. So far we are getting this error when calling 'sessions', and 'roster'.

**Comment by guusdk** [comment]
Thanks for reporting this. I have rushed a provisional fix for you in https://github.com/igniterealtime/openfire-restAPI-plugin/pull/201

Can you test that fix please?

**Comment by Devocity81** [comment]
> The change should be available in the latest 'snapshot' build of the plugin that can be downloaded from https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=restAPI

We downloaded the plugin from the link you shared, installed the plugin and restarted the server, but we are still seeing the same error message.

**Comment by guusdk** [comment]
Hmm, that is unexpected. Can you please confirm which version you used? It should be `1.11.1-SNAPSHOT`.

**Comment by Devocity81** [comment]
> Hmm, that is unexpected. Can you please confirm which version you used? It should be `1.11.1-SNAPSHOT`.

I apologize, the wrong version was installed. After installing the correct version, it is now working as expected. I want to thank you again for resolving this issue so fast, we really appreciate it.

**Comment by Devocity81** [comment]
I know this is probably not the correct place to ask this question, I didn't want to ask a question via opening a new issue as it's not an issue. If you could point me to the correct place to ask the following question, I would greatly appreciate it.

We don't use active directory, our users and passwords are managed via a custom implementation. We are looking to for information related to managing users externally directly using the OfUser Jive database table. What encryption is used? How is the Server and Store key calculated and the salt.

Again I know this is not the correct forum for this, any information would be greatly appreciated.

Thanks,
Patrick Shaffer

**Comment by akrherz** [comment]
> I know this is probably not the correct place to ask this question,

Ask here https://discourse.igniterealtime.org/
