### ISSUE TITLE
1.3.8 versions doesn't work with Openfire 4.2.3

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-restAPI-plugin#21]
REST API menu shows blank page. Similar to https://github.com/igniterealtime/openfire-dbaccess-plugin/issues/2
Forums post https://discourse.igniterealtime.org/t/rest-api-plugin-1-3-8-rest-api-jsp-not-found/84551

**Comment by wrooot** [comment]
Sorry, didn't realize there are two REST API repos :) Moved.

**Comment by GregDThomas** [comment]
The 1.3.9-SNAPSHOT from https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=restAPI should work now with Openfire 4.2.x and 4.3.x

I've not released it - I'll leave that to Roman in case he wants to include other changes.
