### ISSUE TITLE
Safety check over empty message type is not correct

### ISSUE THREAD

**Issue by Lourival-ETI-BR** [igniterealtime/openfire-restAPI-plugin#24]
Safety check over empty message type is not correct. The first check for null over getType() is followed by check for length over "getTo()" into MUCRoomController.java line 410:

            if (message.getType()!=null && message.getTo().toString().length()!=0)
                mucMsgEntity.setType(message.getType().name());

**Comment by Redor** [comment]
What would be your recommendation?

**Comment by Redor** [comment]
Thy for the comment. It is fixed in: https://github.com/igniterealtime/openfire-restAPI-plugin/releases/tag/1.3.10
