### ISSUE TITLE
Use better HTTP Status code than 500 when resource already exists.

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-restAPI-plugin#35]
As reported on https://discourse.igniterealtime.org/t/openfire-returning-500-internal-server-erro-when-user-already-exist/84217

> I’m getting 500 INTERNAL SERVER ERROR while trying to create user via REST API.
> Later I found that User ID already exist. Is there any other way to get different response when user already exist (instead of 500 internal server error)?
> 
> Openfire 4.3.2
> REST API 1.3.7

**Comment by Redor** [comment]
I introduced a better handling for such errors (exactly that case is also fixed)
