### ISSUE TITLE
Requests fail when using XML as accept type on Openfire servers running java 11

### ISSUE THREAD

**Issue by nsobadzhiev** [igniterealtime/openfire-restAPI-plugin#39]
Recently I switched to using Java 11 on my Openfire server (Openfire 4.6.0).
All is well, but while using the REST API plugin with the java client library, I was getting 500s as response to queries (the `users` endpoint, I believe).

As vaguely mentioned in #36, I tried to switch to using JSON as accepted content type. 
Using the java client library, that would be (in Kotlin):

```
RestApiClient(
            chatServerUrl,
           chatServerPort,
            AuthenticationToken(secret),
            SupportedMediaType.JSON
            )
```

That fixed the issue. However, I'm wondering if that's a known issue and if there's a planned fix. I assume it's a problem with the XML parser not really supporting Java 11, but maybe someone here knows more.

Some versions:
Openfire: 4.6.0
REST API plugin: 1.4.0
Java container: openjdk:11-jre-slim

**Comment by ErwanF76** [comment]
To me, this issue is similar to Java 11 Jaxb issue #25.
I posted already my feeback there.
It would be great to correct this in the near future :)

**Comment by guusdk** [comment]
I suspect that this problem no longer occurs on Openfire 4.6.2 and later, as a result of https://igniterealtime.atlassian.net/browse/OF-2196. In my environment (Openfire 4.7.0-beta on Java 11), this I do not seem to have any issues. Please re-open this issue if you can prove me wrong.
