### ISSUE TITLE
Unable to add External/Remote users to a group

### ISSUE THREAD

**Issue by droobah** [igniterealtime/openfire-restAPI-plugin#40]
I am trying to automate added users from a remote s2s system to groups in OpenFire.
It would be nice to have functionality to add users by their full JID.  Does this functionality exist and I just missed it?

I have implemented this in my fork by adding a setGroupMembers function that allows me to overwrite all members with a list of JIDs.

https://github.com/droobah/openfire-restAPI-plugin/commit/a4828130944e584bdb76964944ca9864c4ad6199

**Comment by jalbarran** [comment]
I guess this fix broke "Add user to group" api, when the group does not exist
