### ISSUE TITLE
Can not create users by API 1.4.0

### ISSUE THREAD

**Issue by kipa-zhang** [igniterealtime/openfire-restAPI-plugin#43]
Can not create users by (http://example.org:9090/plugins/restapi/v1/users)
Response 500
Openfire Log is following:
![image_2020_07_15T02_49_41_448Z](https://user-images.githubusercontent.com/15901548/87498590-bd2f4680-c68a-11ea-8a4d-b62789cbb471.png)

**Comment by kipa-zhang** [comment]
![image_2020_07_15T02_50_25_816Z](https://user-images.githubusercontent.com/15901548/87498639-dc2dd880-c68a-11ea-8d04-b39120a744e7.png)
This is my testing, any idea?

Openfire: 4.3.2
RestAPI: 1.4.0

**Comment by Redor** [comment]
Check the example here: https://www.igniterealtime.org/projects/openfire/plugins/1.3.8/restAPI/readme.html#create-a-user

You can't create multiple users at once. Instead you have to create one by one with the body:

```
{
    "username": "admin",
    "password": "p4ssword",
    "name": "Administrator",
    "email": "admin@example.com"
}
```

**Comment by kipa-zhang** [comment]
> Try to create the user with the payload of:
> 
> ```
> {
>     "username": "admin",
>     "password": "p4ssword",
>     "name": "Administrator",
>     "email": "admin@example.com"
> }
> ```

So this is not working now?
![image_2020_07_16T02_57_32_757Z](https://user-images.githubusercontent.com/15901548/87621351-31352180-c753-11ea-81f9-854517542d54.png)
