### ISSUE TITLE
GET /plugins/restapi/v1/users/{username} is returning 500 errors

### ISSUE THREAD

**Issue by sathishkpm** [igniterealtime/openfire-restAPI-plugin#46]
Hi There,

There is an issue with OpenFire (4.6.0) RESTAPI plug-in (1.4.0) when we are trying to get the users we are getting 500 errors.

Creating a group also having same issue.

Could you please let us know what is the issue with this.

**Comment by admc-development** [comment]
Hey was this ever resolved?

**Comment by bernard-ng** [comment]
I'm using RESTAPI plug in 1.6.0, this issue is already fixed

**Comment by akrherz** [comment]
Thanks, will close issue until we hear otherwise that it still remains a problem.
