### ISSUE TITLE
Is there any endpoint for the group group chat settings ?

### ISSUE THREAD

**Issue by nicolasduminil** [igniterealtime/openfire-restAPI-plugin#48]
Hello, I need an endpoint to manage the conference service such that to modify its properties, its administrators and its room creation permissions, Is there any ?

**Comment by Fishbowler** [comment]
For the entire service, rather than individual rooms?
Doesn't appear so. https://github.com/igniterealtime/openfire-restAPI-plugin/tree/master/src/java/org/jivesoftware/openfire/plugin/rest/service - all of these take roomName

**Comment by nicolasduminil** [comment]
Yes, for the entire conference service. The equivalent of what the admin console provides by navigating to Group Chat and then Properties, or Administrators, or room creation permissions. Perhaps I could write a customized API taking one of these services as an example ? Is that complicated ?

**Comment by Redor** [comment]
Hi @nicolasduminil, unfortunately, you can't adjust/create a conference service, but just the rooms inside the conference service.
