### ISSUE TITLE
How can I send a message to somebody by http?

### ISSUE THREAD

**Issue by maobiwen** [igniterealtime/openfire-restAPI-plugin#53]
I want send a message to somebody from  somebody by http 
for example ,when a user create an order ,I want to remind him to pay it ,so I must send a message to him from system by http

**Comment by guusdk** [comment]
This issue tracker is intended to be used to track feature requests and bugs in the software. It is not intended as a way to ask for help. Please do not create issues if you're looking for advise or help.

You can seek help from the Ignite Realtime Community in various ways. Typically, asking questions in https://discourse.igniterealtime.org/ is a good start.
