### ISSUE TITLE
v1.5.0 does not work with Openfire 4.6.1 and later

### ISSUE THREAD

**Issue by tenaciousRas** [igniterealtime/openfire-restAPI-plugin#56]
Openfire v4.6.0 works with v1.5.0. However, v4.6.3 is incompatible due to this change in LocalMUCRoom: 

`private List<String> rolesToBroadcastPresence`

changed to

`private List<MUCRole.Role> rolesToBroadcastPresence`

If we want a v1.5.1 patch to deal with this, then we should probably tag v1.5.0 now.

pls. see https://github.com/igniterealtime/Openfire/pull/1831

**Comment by tenaciousRas** [comment]
I have a patch tee'd up. I think we need the v1.5.0 tag to handle a PR properly

**Comment by guusdk** [comment]
The change that @tenaciousRas mentioned got added in Openfire 4.6.1 as a result of the fix for issue OF-2168.

**Comment by guusdk** [comment]
The annoying bit that's preventing an easy fix is that Openfire's artifacts for version 4.6.1 through 4.6.3 never made it into the Maven repository.
