### ISSUE TITLE
endpoint `groups` the `members` returns empty instead of all members inside

### ISSUE THREAD

**Issue by ruicaramalho** [igniterealtime/openfire-restAPI-plugin#62]
I'm using Groups and users from Active Directory.

**Comment by ruicaramalho** [comment]
I'm using Groups and users from Active Directory.

**Comment by Fishbowler** [comment]
`/restapi/v1/groups` returns the top level information, whilst `/restapi/v1/groups/SomeGroupName` returns membership information. The docs aren't clear on that. For a large number of groups, I imagine the payload could be large, and the delay considerable. For now, I'll work on updating the docs to ensure this is clean.

**Comment by ruicaramalho** [comment]
With Openfire 4.7.1 and Rest API 1.8.0 is now working fine...
Thanks

**Comment by ruicaramalho** [comment]
Example of a return:
~~~~
{
    "groupnames": [
        "Informatica"
    ]
}
~~~~
