### ISSUE TITLE
Add ability to perform dependency checking

### ISSUE THREAD

**Issue by Fishbowler** [igniterealtime/openfire-restAPI-plugin#77]
Given the security implications of the plugin, both in terms of the additional surface area this adds to Openfire, and the depth of change or damage or egress possible from a compromise of the REST API plugin, keeping dependencies up-to-date is important.

Add a dependency check to maven to perform a deep scan of the dependency tree to ensure quick resolution of any discovered CVEs.

**Comment by guusdk** [comment]
Is this something that we should consider pushing upstairs, to the parent POM defined in Openfire that's used by most plugins?

**Comment by Fishbowler** [comment]
Oooh, yeah, that sounds like an awesome plan. How would that work? It gets published as an effect of OF 4.7.0, and then anything with a min version gets it?

**Comment by guusdk** [comment]
I'm not sure if it would work (I'm not sure if profiles are inherited, things like that), but I'd imagine that we could try following the same route as what's being used for Admin Console page JSP compilation: most (if not all) plugins declare their parent to be `org.igniterealtime.openfire:plugins` (as defined in https://github.com/igniterealtime/Openfire/blob/master/plugins/pom.xml), so if we add the profile there, then every plugin that starts depending on the version of that parent pom that includes that profile... should automatically inherit it?
