### ISSUE TITLE
Inconsistent JSON representation

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-restAPI-plugin#79]
The JSON response generated by various versions of the plugin isn't consistent. See https://discourse.igniterealtime.org/t/rest-api-breaking-change-in-json-roster-response-in-1-6-0/

**Comment by EKMMattV** [comment]
Following on from the discourse discussion I made a quick test using @JsonProperty on the RosterEntities.getRoster() method:
```java
import com.fasterxml.jackson.annotation.JsonProperty;
...
    @XmlElement(name = "rosterItem")
    @JsonProperty("rosterItem")
    public List<RosterItemEntity> getRoster() {
        return roster;
    }
```
This fixed the JSON response in my environment, as hoped.

I would point out there are a large number of other `@XmlElement` and `@XmlElementWrapper` uses throughout the classes in the entity package: they would all need review to determine if they are overriding the default bean naming pattern (many are not), and if so whether they also require a `@JsonProperty` annotation to fix the JSON representation.

Doubling up these annotations everywhere feels like pretty poor form. Reading around it seems Jackson2 might be able to honour the same annotations for both JSON and XML serializations if you use just one flavour, but I haven't had time to investigate.

**Comment by guusdk** [comment]
I believe that the proper way of telling Jackson to look at (and even prefer) JAXB annotations is by using https://github.com/FasterXML/jackson-modules-base/tree/master/jaxb

I've applied that in the PR that is now linked to this issue. @EKMMattV can you test if this works for you please?
