### ISSUE TITLE
System Properties endpoint only returns user set properties

### ISSUE THREAD

**Issue by Fishbowler** [igniterealtime/openfire-restAPI-plugin#80]
Calling `/restapi/v1/system/properties` on a new instance returns 15-20 entries, whereas the System Properties page shows well over 100.

(Perhaps migrating from JiveGlobals to SystemProperty would give access to them all? Or do we still need to use both, like SystemPropertiesServlet does?)

**Comment by GregDThomas** [comment]
SystemProperties are stored under the cover alas JiveGlobals. The SystemProperties just offers additional functionality (e.g. a description, pretty printing, validation etc. ). So JiveGobals are a superset of SystemProperties. If you iterating over JiveGobals you’re getting them all; if you’re iterations over SystemProperties you’ll only get some, but certainly more than 29 or so I would think.

**Comment by guusdk** [comment]
Should be fixed with #80
