### ISSUE TITLE
Perform a release

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-restAPI-plugin#85]
With the Openfire 4.7.0 release, I'd prefer to quickly have a release of this plugin too. What do we need to put in before can draw a release?

I'd personally like at least these to go in:
- https://github.com/igniterealtime/openfire-restAPI-plugin/pull/84
- https://github.com/igniterealtime/openfire-restAPI-plugin/pull/83

What do you think?

**Comment by Redor** [comment]
I would be fine with that.

**Comment by Fishbowler** [comment]
Done and done.

**Comment by Fishbowler** [comment]
See #86
