### ISSUE TITLE
Add endpoints for readiness and liveness

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-restAPI-plugin#92]
Provide endpoints that can be used by orchestrators of auto-scalable environments, like Kubernetes. I'll mostly use Kubernetes definitions in this issue (taken from https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).

Many applications running for long periods of time eventually transition to broken states, and cannot recover except by being restarted. Kubernetes provides liveness probes to detect and remedy such situations. To facilitate such probes, our plugin should provide an endpoint that returns an HTTP Status code outside of the 200-399 range, when Openfire is in a state where it requires a restart. 

For liveness checks, these conditions come to mind:
- When a deadlock is detected: `ManagementFactory.getThreadMXBean().findDeadlockedThreads()` returns non-null.
- a system property that reports that a restart is required, after a change was applied. Caveat: this could lead to a scenario where a server is being restarted while property changes are being made.
- cache consistency checks. Caveat(s): we know that there are issues with these, and they may automatically recover.

Readiness probes are used to know when a container is ready to start accepting traffic. Sometimes, applications are temporarily unable to serve traffic. For example, an application might need to load large data or configuration files during startup, or depend on external services after startup. In such cases, you don't want to kill the application, but you don't want to send it requests either. Kubernetes provides readiness probes to detect and mitigate these situations. A pod with containers reporting that they are not ready does not receive traffic through Kubernetes Services.

For readiness checks, these conditions come to mind:
- All (non-disabled) Connection Managers are ready to accept data
- The plugin manager has finished executing its initial run to load all plugins upon boot
- `XmppServer.isStarted()` returns `true`
- When clustering is enabled, clustering reports 'ready'

**Comment by guusdk** [comment]
Reopening: I forgot to add this to the Markdown-based documentation.

**Comment by Fishbowler** [comment]
Docs are in 👍
