### ISSUE TITLE
Don't require authentication for system readiness endpoints

### ISSUE THREAD

**Issue by Fishbowler** [igniterealtime/openfire-restAPI-plugin#96]
In #92, the plugin gained the ability to respond to simple requests for whether Openfire was "ready".
This still requires authentication which isn't always available in network load balancers and the like.

Add an AuthFilter exclusion for these paths.

**Comment by Fishbowler** [comment]
Is adding an exclusion for these paths in the AuthFilter too simple an approach? Does it raise the risk of a DoS attack?

**Comment by guusdk** [comment]
> Is adding an exclusion for these paths in the AuthFilter too simple an approach? Does it raise the risk of a DoS attack?

Possibly add an network-address-based whitelist (either for all services, or for unauthenticated services only, or both) to overcome this?

**Comment by guusdk** [comment]
As an aside: since this is a plugin to Openfire, by the time that any API requests are responded to with an authentication error (instead of a timeout), you'll known that Openfire has at least started loading all plugins, and therefore is close to being ready.
